services:
  # Node.js Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: football-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run docker:dev
    networks:
      - app-network
  
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: football-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
    env_file:
      - .env
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge